# Generated by Django 3.2 on 2021-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
    ]
